# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
data-path="data"
genesis-file="../genesis.json"
logging="INFO"
# node-private-key-file="/keys/nodekey"
 
p2p-enabled=true
rpc-http-api=["ETH","NET","QBFT"]
host-allowlist=["*"]
rpc-http-cors-origins=["all"]
